package com.zrd.zr.game;

import java.io.Serializable;

public class ScoreRecord implements Serializable {
	/**
	 * serialVersionUID generated by eclipse
	 */
	private static final long serialVersionUID = -1996334840165971903L;
	String mName;
	int mScore;
	
	public ScoreRecord (String name, int score) {
		this.mName = name;
		this.mScore = score;
	}
}
